#+CATEGORY: day

* TODO Trainer Kimmy's Food Plan
This week's objectives:

1. [X] *Consistent schedule:* eat a substantial meal at consistent times. For this first week, I can eat whatever I like.
  |           | Scheduled | Actual time | What?                    |
  | Breakfast | 10am      |       10:13 | Omelette, wrap,          |
  | Lunch     | 12pm      |       12:43 | Subway protein bowl      |
  | Dinner    | 4pm       |        4:59 | Turkey burg and pasketti |

2. [ ] *Limited snacks:* Outside my meals, I can eat as much tea/water or veggies as I like.

3. [X] *Calories:* All calories are logged in LoseIt and I'm not in the red.

*** Why these goals?
Doing this *makes my choices ahead of time.* No need to agonize about /when/ to eat; I've already decided. And I'm sure my imagination will gear me up for /what/ to eat.

At the same time, I want this to *feel like a challenge* enough to get a sense of accomplishment when I'm able to do this

*** Non-goals
- Portion control
- Adjusting actual meal content (consider slow-carb or keto-like)

** Things to be conscious of (check when i notice them)
- [ ] *Overthinking:* I don't want to start out controlling /what/ I eat just yet. My goal this week is consistency. That means I'll get out the candy and save it for the next meal time!
- [X] *Moments of hunger:* when my tummy feels rumbly or sick to my stomach
  - Failure plan: when I notice this, immediately drink some cold water.
- [X] *"That wasn't so bad"*: when I'm able to pull out of a dive and it was easier than I expected.
- [ ] *Schedule isn't working?* Revise as needed.

** Thoughts
This morning in the shower I was kinda worried and felt *sick to my stomach,* feeling overwhelmed by the plan I'm making. What if it's too much? But then I *drank some water* and started planning this in my journal, and I'm feeling better.

I think the time between breakfast and lunch is way too short, OR I think I overate for breakfast. Not hungry at all for lunch, eating a light-carb lunch anyway to stay consistent.

Super late for lunch too, in part because I wasn't feeling so hungry and in part because I went shopping just before!

For dinner I found I really wasn't that hungry! So much protein + salad before was really filling me up. But I ate anyway; I guess it worked out.
